### ISSUE TITLE
ResizableBufferAdapter<Data>::resize() is broken

### ISSUE THREAD

**Issue by TankTheFrank** [cocos-creator/cocos2d-x-lite#1023]
Calling resize() with a smaller size than current buffer does nothing. This breaks all expectations considering how virtually every container out there handles resize() and breaks any chained processors that need a smaller sized buffer.

Everywhere else resize() is resize() but for Data resize() is reserve()

**Comment by dumganhar** [comment]
Good finding.
This code is came from Cocos2d-x, actually, we need to fix it.
Thanks for your feedback.

**Comment by TankTheFrank** [comment]
My local fix is fairly simple, for smaller sizes I'm just calling fastSet() with the existing bytes buffer and the new size, all we need is to set the new private 'size' value without re-allocating anything.

**Comment by dumganhar** [comment]
@TankTheFrank, yep, your fix is good. But it will waste some memory.
To make the behavior more correct, I think we need to `realloc` the memory if the size is lower than before.

**Comment by dumganhar** [comment]
fixed at https://github.com/cocos-creator/cocos2d-x-lite/pull/1028.
Thanks for your feedback.
