### ISSUE TITLE
cc.PolygonCollider 原生和 浏览器渲染方式不一样？？？

### ISSUE THREAD

**Issue by 13yd** [cocos-creator/cocos2d-x-lite#1037]
测试demo 帮忙看看 微信浏览器下 不算一个 calldraw

app 下面 算一个 calldraw ？？？ 
导致 app calldraw 无法 进行游戏下一步 
测试demo
http://forum.cocos.com/uploads/default/original/3X/d/1/d18a482eb3c6768fbc624b5e0066411344852d86.zip

网页 没问题 app 卡成狗
addComponent(cc.BoxCollider); 
cc.BoxCollider
cc.PolygonCollider 这2个 组件 感觉有问题 app 上面

cc.CircleCollider 圆形碰撞组件 是没有问题的 
可是 检查不能全是圆的吧 鱼不是胖子

**Comment by jareguo** [comment]
关闭 debug mode 就行了，不是 bug
