### ISSUE TITLE
JS层自定义Action的实现应该重新考虑

### ISSUE THREAD

**Issue by WenhaiLin** [cocos-creator/cocos2d-x-lite#1082]
https://github.com/cocos-creator/cocos2d-x-lite/blob/efadf0beb4b21834e8d58a2ffb0f065cd79c2b7d/cocos/2d/CCAction.h#L187

https://github.com/cocos2d/cocos2d-x/commit/badd80bf3aa7b5cecaa494c748075bdd74783da7

实现自定义action完全是个级别很低的需求，而且这个实现方案实在蛋疼

update：
可以考虑在JSB那一层新增一个ActionInterval的子类来满足这个需求

每个action都发update事件到JS层是什么鬼。。。

**Comment by jareguo** [comment]
感觉 action 整个都在 js 层实现就行了

**Comment by WenhaiLin** [comment]
@jareguo 哈哈，工作量不小. 我这先简单自己移除这个事件派发
听说你们准备native层只保留渲染等基础功能

**Comment by tangyiyang** [comment]
Javascript的跨语言调用消耗是非常高的。
考虑每帧都去跨语言，在几十上百个Action的条件下（很多动画很容易达到这个条件），并且每次跨语言，都会产生一些小对象，对内存GC也非常不友好。

**Comment by dumganhar** [comment]
2.0, 2.0, 2.0
世界就太平了。

**Comment by WenhaiLin** [comment]
cocos creator当前基于这个事件同步JS逻辑数和Native渲染数，还去不得。。。
