### ISSUE TITLE
Fixture对象销毁导致的异常

### ISSUE THREAD

**Issue by zqxiaojin** [cocos-creator/cocos2d-x-lite#1261]
详情见 http://forum.cocos.com/t/undefined-is-not-an-object-evaluating-colliderb-body/60184/12?u=lucky_06

问题有2个：
一是 _disableChildComps 这个函数，在删除component的时候，body有可能比其对应的 Collider 更早被destroy，这就导致Collider 在destroy的时候，没法获取到body对象从而执行 DestroyFixture，导致部分Fixture对象泄露。

二是 当Fixture能稳定Destroy的时候，由于其关联的对象使用了对象池。导致 jsbinding 被误消除。

**Comment by zqxiaojin** [comment]
发现修改的代码在 engine 那里，转过 https://github.com/cocos-creator/engine/issues/2726

**Comment by zqxiaojin** [comment]
我发现， engine项目只能修正问题一，问题二需要在该项目修正

**Comment by zqxiaojin** [comment]
对于问题二，需要在本项目进行修改，见 #1263

**Comment by jareguo** [comment]
fixed
