### ISSUE TITLE
the label in button position wrong on native when using TTF font

### ISSUE THREAD

**Issue by drelaptop** [cocos-creator/cocos2d-x-lite#1403]
测试版本： creator 版本 creator 1.9.1

Button 中的 Label 使用 TTF 字体时出现，位置偏上

运行在浏览器状态正常，运行在模拟器时异常，推测在所有原生平台异常。如图

![ttf-label-button-position-wrong](https://user-images.githubusercontent.com/26329291/42930679-4000e648-8b70-11e8-92ce-491e2ed11039.png)

**Comment by drelaptop** [comment]
目前的现象是新建一个 Button，将 Button 下 Label 设置 TTF 字体，保持默认设置，无论如何设置垂直对齐方式。文本总是表现出向上对齐。

## 原因

编辑器给出的默认行高，有问题，对齐时行高参与了垂直位置的计算。

- 单独新建一个 Label，行高和字体大小一致，都是 40
- 新建一个 Button，可以发现 Button 下 Label，字体大小 20，行高 40

**Comment by sky068** [comment]
到1.9.2版本为止，这个问题一直都存在。

**Comment by drelaptop** [comment]
@jareguo 麻烦关注一下

**Comment by jareguo** [comment]
所以把行高改回 20，就好了吗？ 麻烦 @umbrellaPP 解决一下，有疑问可以咨询 @knoxHuang

**Comment by drelaptop** [comment]
是的，默认值行高改为 20，改完后验证一下垂直对齐在 web 和 native 是否有效 @umbrellaPP

**Comment by umbrellaPP** [comment]
好的，我晚点处理下这个问题
