### ISSUE TITLE
引擎定制出错windows

### ISSUE THREAD

**Issue by kiki882727** [cocos-creator/cocos2d-x-lite#1409]
我按照官方文档http://docs.cocos.com/creator/manual/zh/advanced-topics/engine-customization.html 来定制引擎
环境是win7
vs2015, python(2.7.14) node (8.11.3) gulp(3.9.1) ndk  r10c 
cocoscreator版本是 1.9.3  fork位置是18-7-4的v1.9-release
gulp gen-libs  在做这一步的时候报错
 F:\env\android\android-ndk-r10c\ndk-build.cmd NDK_PROJECT_PATH=null
...
...
externalNativeBuildRelease: not building target network because it isn't in targets set
externalNativeBuildRelease: not building target audioengine because it isn't in targets set
externalNativeBuildRelease: not building target jscocos2d because it isn't in targets set
externalNativeBuildRelease: not building target spine because it isn't in targets set
...
E:\engine\personal_engin\cocos2dx\cocos/network/../platform/CCPlatformConfig.h:143:6: error: #error "Cannot recognize the target platform; are you targeting an unsupported platform?"

有人知道怎么回事吗？

**Comment by drelaptop** [comment]
```
E:/engine/personal_engin/cocos2dx/tools/simulator/frameworks/runtime-src/proj.android-studio/app/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/objs/cocos2d_simulator_static/__/lib/protobuf-lite/google/protobuf/stubs/atomicops_internals_x86_gcc.o.d
```

261 个字节，路径太长，Windows 默认最多识别 256，将 `cocos2dx` 放根目录，或者参考中文论坛 http://forum.cocos.com/t/3-17-lua/60857

**Comment by kiki882727** [comment]
@drelaptop 谢谢
