### ISSUE TITLE
重新编译 libpng，将频繁出现的 stderr 改为 stdout

### ISSUE THREAD

**Issue by drelaptop** [cocos-creator/cocos2d-x-lite#1451]
相关的 issue, https://github.com/cocos-creator/fireball/issues/7849

`known incorrect sRGB profile` 错误信息，实际是一个提示信息，将 stderr 改为 stdout。避免编辑器输出红色信息，对开发者造成误导。

**Comment by PatriceJiang** [comment]
根据源码的注释
```
    /* These profiles are known to have bad data that may cause
    * problems if they are used, therefore attempt to
    * discourage their use, skip the 'have_md5' warning below,
    * which is made irrelevant by this error.
    */
    png_chunk_report(png_ptr, "known incorrect sRGB profile",
    PNG_CHUNK_ERROR);
```
和stackoverflow上的讨论 https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile, 在creator中提供修复png文件的工具应该是比较合理的解决方法.

**Comment by drelaptop** [comment]
我认为编辑器将 __这样的在错误流的警告日志__ 转为 __编辑器的 warning 日志__，也是个合理的做法。https://github.com/cocos-creator/fireball/issues/8254
