### ISSUE TITLE
XMLHttpRequest,WebSocketAPI 失效.

### ISSUE THREAD

**Issue by geliangdashen** [cocos-creator/cocos2d-x-lite#1474]
COCOS官网文档称 XMLHttpRequest,WebSocketAPI 可以跨手机native平台.
但在android平台上失效,报错信息为:
> 08-23 17:24:20.667 13633-13727/org.cocos2d.helloworld D/libc-netbsd: getaddrinfo: echo.websocket.org get result from proxy gai_error = 0

似乎是域名解析出了问题.
测试设备魅族pro7,CococsCreator 1.8.1
测试代码如下
```javascript
 this.websocket.node.on('click',function () {
            var ws = new WebSocket("ws://echo.websocket.org");
            ws.onopen = function (event) {
                console.log("Send Text WS was opened.");
            };
            ws.onmessage = function (event) {
                console.log("response text msg: " + event.data);
            };
            ws.onerror = function (event) {
                console.log("Send Text fired an error");
            };
            ws.onclose = function (event) {
                console.log("WebSocket instance closed.");
            };

            setInterval(function () {
                if (ws.readyState === WebSocket.OPEN) {
                    ws.send("Hello WebSocket, I'm a text message.");
                }
                else {
                    console.log("WebSocket instance wasn't ready...");
                }
            }, 3000);
        },this);

        this.http.node.on('click',function () {
            var xhr = new XMLHttpRequest();
            xhr.onreadystatechange = function () {
                if (xhr.readyState == 4 && (xhr.status >= 200 && xhr.status < 400)) {
                    var response = xhr.responseText;
                    console.log(response);
                }
            };
            xhr.open("GET", "https://fluttergo.com/", true);
            xhr.send();
        },this);
```

------------------------------
引用文档如下(http://docs.cocos.com/creator/manual/zh/scripting/network.html?h=mlhttprequest)
> 标准网络接口
在 Cocos Creator 中，我们支持 Web 平台上最广泛使用的标准网络接口：
XMLHttpRequest：用于短连接
WebSocket：用于长连接
当然，在 Web 平台，浏览器原生就支持这两个接口，之所以说 Cocos Creator 支持，是因为在发布原生版本时，用户使用这两个网络接口的代码也是可以运行的。也就是遵循 Cocos 一直秉承的 “一套代码，多平台运行” 原则。

**Comment by geliangdashen** [comment]
在win平台使用websocket 连接服务器 报错如下:
D/jswrapper (125): JS: Send Text fired an errorwss://alphagateway.matchvs.com err {"type":"error","target":{"url":"wss://alphagateway.matchvs.com","URL":"wss://alphagateway.matchvs.com","protocol":""}}

**Comment by PatriceJiang** [comment]
@geliangdashen 我验证过测试用例，没有出错。 
- 域名解析问题，你可以切换网络再试试。 
- 第二个报错能否提供相对完整的log，方便分析？

**Comment by geliangdashen** [comment]
- 第一个问题换个手机确实可以.
- 第二个问题错误出现在上述测试代码的这个位置
```javascript
 ws.onerror = function (event) {
                console.log("Send Text fired an error");
            };
```
推测 websocket建立连接时tls/ssl 出错.

**Comment by geliangdashen** [comment]
上述问题目前是仅使用ws解决.  至于SSL是否支持的问题未进行测试. 

不得不说, Cocos的 websocket的API与 chrome等浏览器的实现还是存在差异.需要额外的适配 , 比如close()/onClose()函数 ;  文档不够详细 ,  需要开发者自行阅读源码摸索 .
