### ISSUE TITLE
js自动绑定工具支持c++中多继承关系的绑定吗?

### ISSUE THREAD

**Issue by fengsiri** [cocos-creator/cocos2d-x-lite#1511]
如题

**Comment by drelaptop** [comment]
什么叫多继承关系的绑定？能否解释一下

**Comment by fengsiri** [comment]
假如在c++中有一个子类D继承了多个父类P1,P2,P3, 子类和每个父类都可以构建出各自的对象实例,且子类D的对象实例可以调用父类的方法,.同样的,我希望在js中同时注入类D和它的父类P1,P2,P3,并且在js中也能new出各自实例,并且子类D的js对象实例也可以调用父类的方法.但是在js世界的原型链上只能存在一个直接父类,其他父类需要通过mixin方式将自身方法复制拷贝到这个父类上.
我在看js自动绑定工具生成的c++绑定代码时,好像没发现有mixin操作,只有一个在原型链上设置父类的v8 api调用.所以不太确定是否支持这种c++多继承情况下的绑定, 难道mixin操作是用js代码实现的?

**Comment by fengsiri** [comment]
也就是说cocos-2d在绑定时并没有这种多继承的情况,是吧

**Comment by drelaptop** [comment]
是的，没有多继承关系的绑定

**Comment by fengsiri** [comment]
明白了,谢谢
