### ISSUE TITLE
How to build libjs_static.a by myself?

### ISSUE THREAD

**Issue by quabug** [cocos-creator/cocos2d-x-lite#157]
I'm try to build game by using ndk clang with modified version of `build_android.py` and `Application.mk`, which use `APP_STL := c++_static` instead of `gnu_stl`.

But `libjs_static.a` seems built by `gcc` and `gnu_stl` which produce some errors like
`C:/proj/cocos_creator_test/build/jsb-default/frameworks/cocos2d-x/external/android/armeabi/libjs_static.a(jscntxt.o)(.text+0xb8c): error: undefined reference to 'std::ios_base::ios_base()'` during linking.

So my question is how can I build `libjs_static.a` from source? Then I could use `clang` and `c++_static` to build my own `libjs_static.a`.

Thanks

**Comment by drelaptop** [comment]
> So my question is how can I build libjs_static.a from source? Then I could use clang and c++_static to build my own libjs_static.a

using clang to build android is finished recently, please refer to https://github.com/cocos-creator/cocos2d-x-lite/pull/1385
