### ISSUE TITLE
[creator 2.1] 简单的demo会导致iphone5s和iphone6 崩溃

### ISSUE THREAD

**Issue by xianyinchen** [cocos-creator/cocos2d-x-lite#1617]
做一个demo，只是不停的打印日志，20+分钟就会崩溃。
来自论坛：https://forum.cocos.com/t/bug-bug-bug-ios-2-0-x-bug/70279/9

[test 2.zip](https://github.com/cocos-creator/cocos2d-x-lite/files/2647974/test.2.zip)

**Comment by drelaptop** [comment]
- 直接用模拟器输出了 40 分钟日志，编辑器卡死 @wuzhiming 

![image](https://user-images.githubusercontent.com/26329291/53220251-807e3c00-369e-11e9-9939-e91f3f3154ba.png)

**Comment by aiversonwk** [comment]
求关注，后台很多相同崩溃，都在jsc内部，毫无头绪

**Comment by drelaptop** [comment]
@MrQQQQQQQQQQ @aiversonwk 

崩溃在 `JSB_console_log ` 中参考上面的 PR 规避，如果是崩溃在其它地方也是 `call` 的时候，可以从考虑`对应的 js 对象是否被 GC 掉了`入手

**Comment by aiversonwk** [comment]
@drelaptop 你说的`对应JS对象`应该怎么查看呢，有时候在xcode中直接崩溃，但没有办法看到是哪个对象引起的，求教

**Comment by drelaptop** [comment]
https://github.com/cocos-creator/cocos2d-x-lite/pull/1687#issuecomment-466999671 根据堆栈看，比如这里的对应 js 对象就是 `__oldConsoleLog`，脚本引擎 init 时 getProperty 保存的
