### ISSUE TITLE
Simulator not found in cocos2d-x path

### ISSUE THREAD

**Issue by efares** [cocos-creator/cocos2d-x-lite#164]
I'm not sure if this is an issue or bug but I downloaded the latest version of cocos2d-x-lite and then saw this message in the Preference of Cocos Creator.

![screen shot 2016-06-10 at 9 23 35 pm](https://cloud.githubusercontent.com/assets/4211727/15982287/b7f138ec-2f51-11e6-9a67-0a2e231fe360.png)

**Comment by nantas** [comment]
You'll need to generate simulator yourself, checkout the readme of this repo
