### ISSUE TITLE
creator2.0.9 win7 构建Android工程后，NDK目录错误，缺少斜杠“\”

### ISSUE THREAD

**Issue by ayarami** [cocos-creator/cocos2d-x-lite#1729]
[https://forum.cocos.com/t/bug-creator-androidstudio/76934](https://forum.cocos.com/t/bug-creator-androidstudio/76934)
 win7下面，设置了NDK目录后，构建出来AS工程中的NDK目录少了斜杠，2.0.9creator

**Comment by jareguo** [comment]
2.0.10 将会修复~
