### ISSUE TITLE
Simulator iOS Build fail

### ISSUE THREAD

**Issue by masteage** [cocos-creator/cocos2d-x-lite#1735]
* **Error**
```
ld: entry point (start) undefined.  Usually in crt1.o for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

* **Status**
    * branch - develop (fe77b20f)
    * Xcode Version (8.2.1 , 10.1)

**Comment by masteage** [comment]
bug fix (9e7e1b7)

**Comment by minggo** [comment]
Thanks for the PR, but i don't know why change to 8.0 can work.

**Comment by masteage** [comment]
* i think. maybe xcode system change ?
* i don`t know, perfect min version.

* etc
  * iphone os 5.1.1 is too low version (low xcode support , recent xcode not supprt)
  * my Xcode Version (8.2.1 , 10.1)
  * xcode 8.2.1 able min IPHONEOS_DEPLOYMENT_TARGET is 8.0
    * <img width="383" alt="deployment_target" src="https://user-images.githubusercontent.com/13742619/57358161-c16ef280-71af-11e9-803f-7ef66d74034d.png">

  * maybe others xcode 8.2.1 over version use
  * https://en.wikipedia.org/wiki/Xcode

**Comment by jareguo** [comment]
Thanks
