### ISSUE TITLE
建议使用MMKV重构LocalStorage

### ISSUE THREAD

**Issue by WenhaiLin** [cocos-creator/cocos2d-x-lite#1753]

**Comment by minggo** [comment]
那个平台替换？为什么要这么改？

**Comment by WenhaiLin** [comment]
MMKV性能表现优异

https://github.com/Tencent/MMKV/wiki/iOS_benchmark
https://github.com/Tencent/MMKV/wiki/android_benchmark

**Comment by minggo** [comment]
嗯，从该数据来看，性能确实比较高。但是这样就增加包体了，而且 local storage 不是很频繁调用的吧，不太值得改方案。
