### ISSUE TITLE
Add ability to not stop sound & music on game start in android

### ISSUE THREAD

**Issue by unace** [cocos-creator/cocos2d-x-lite#1770]
Can you please apply this patch https://github.com/cocos2d/cocos2d-x/pull/18640?
Thank you in advance!

**Comment by minggo** [comment]
They are different repos, so should manually synchronize the codes. Why not send a PR for it?

**Comment by unace** [comment]
I made the PR https://github.com/cocos-creator/cocos2d-x-lite/pull/1785 ! thanks, @minggo

**Comment by jareguo** [comment]
done
