### ISSUE TITLE
cocos2d_libs.xcodeproj是如何解决同名文件编译出错的问题的？

### ISSUE THREAD

**Issue by singleD** [cocos-creator/cocos2d-x-lite#1913]
看到cocos2d_libs.xcodeproj项目中有同名的文件，想请教一下这边是如何解决同名文件编译出错的问题的

**Comment by minggo** [comment]
只要不同目录就没关系了啊。

**Comment by singleD** [comment]
我这边已经区分了目录，但是还是有这个问题，应该是有一些特殊设置解决了这个问题，所以想请教一下，并且按照iOS这边来说，只要是同一个项目下，就算是不同目录也不能同名的
![image](https://user-images.githubusercontent.com/12008819/67845254-22adc800-fb3a-11e9-8f6e-e399cf1ec95f.png)
![image](https://user-images.githubusercontent.com/12008819/67845329-4a9d2b80-fb3a-11e9-9c18-a2ca0b9b67aa.png)
![image](https://user-images.githubusercontent.com/12008819/67845373-58eb4780-fb3a-11e9-85a4-f6eeb01ac9dc.png)

**Comment by minggo** [comment]
那你加文件夹的时候选择 `Create folder references` 试试。这时候在 Xcode 里显示的文件夹图标是蓝色的。
