### ISSUE TITLE
建议：creator增加过滤功能

### ISSUE THREAD

**Issue by syxcools** [cocos-creator/cocos2d-x-lite#1932]
项目比较大，文件快过万了，所有文件都在resources里面，但是resources下面会有core，001，002，003，....等多个目录，这些目录功能独立，但是都依赖core目录，任何一个core+001 或者core+002都可以成为一个单独的游戏，开发过程中打开creaotr，太卡了，所以是否可以添加一个filter功能配置，
像git的.gitignore功能一样，如果过滤了，creator启动的时候就不加载了。

备注：这个是一个项目，大厅+很多小游戏，这些小游戏虽然独立，但是逻辑还是统一的，所以如果一个游戏修改，可能要修改好几个游戏，所以不可能一个游戏一个项目去操作，并且出包是一起出的。

**Comment by 284263380** [comment]
因为creator可能是做了监听文件变动的事件，文件数目的增多，会增加监听运行缓慢，所以整个都会卡

**Comment by minggo** [comment]
这个仓库是 lite 的，不是 creator，所以关闭该 issue。
@jareguo creator 的 issue 应该到哪里提？

**Comment by jareguo** [comment]
> creator 的 issue 应该到哪里提？

请移步论坛或者 https://github.com/cocos-creator/engine/issues
我 Transfer 过去吧。
