### ISSUE TITLE
[native] 使用 Freetype 渲染 Label ttf 字体

### ISSUE THREAD

**Issue by PatriceJiang** [cocos-creator/cocos2d-x-lite#2068]
通过使用 Freetype 渲染 Label 组件, 提升性能

- 减少系统调用。 当前的字体渲染依赖平台接口， 在Android上系统调用代价较高。 通过在 C++调用 freetype 统一渲染字符可以提升性能。 
- 使用相同的代码实现 native 的 TTF 文本渲染逻辑。
- 提升 Label 的初始化 和 动态更新的速度。
- 支持复用 字体纹理。 
- 内存平稳

实现类似于U3D 中 TextMeshPro 的功能节点.

-----
进度
- [x]  字体纹理缓存
- [x] 文本布局
- [x] 描边
- [x] 性能测试
- [x] Effect/Material 支持
- [x] 增加 retina 模式
- [x] 释放纹理缓存

bugs
- [x] anchor point

**Comment by minggo** [comment]
Effect 指的是什么？

**Comment by PatriceJiang** [comment]
面板上的 material 属性

**Comment by PatriceJiang** [comment]
修改内容

- [lite external](https://github.com/cocos-creator/cocos2d-x-lite-external/compare/v2.3...PatriceJiang:use_freetype?expand=1)
- [x-lite](https://github.com/cocos-creator/cocos2d-x-lite/compare/v2.3.0-release...PatriceJiang:use-freetype?expand=1)
- [fireball](https://github.com/cocos-creator/fireball/compare/v2.3.0-release...PatriceJiang:use-freetype?expand=1)
- [engine](https://github.com/cocos-creator/engine/compare/v2.3.0-release...PatriceJiang:use-freetype-3)

# 实现说明
//TODO

**Comment by minggo** [comment]
列出来的 `限制` 是修改后带来的新问题，原来没有这些限制吗？

**Comment by caryliu1999** [comment]
1. 引擎层面主要依赖 Canvas 的 API，如果能够保证接口兼容，对于字体显示的影响不会很大，问题就主要在对齐排版上面，当前版本中的 2dx 中 canvas 的实现对 baseline 以及一些字体效果例如阴影都没有支持。SDF的字体支持可以作为一个额外字体支持选项，看需求引擎层面可以添加。

2. 引擎层面可能涉及到 runtime 的问题需要确认

- runtime 对 canvas 的兼容实现是否是沿用的 2dx 的实现，之前遇到的排版问题，runtime 的 canvas 版本好像跟 2dx-lite 还有很多差异，导致后续的引擎修改运行在 runtime 平台出现很多排版问题

- 最新的修改需要新的引擎版本匹配新的2dx版本，runtime 的运行环境应该只有一个固定版本？因为底层 canvas 实现的版本原因是否会导致运行在runtime环境下的字体出现问题

**Comment by PatriceJiang** [comment]
这里的`限制`是由实现的机制推到出来的, 没有参考原本的实现. 比如原本的"字体投影的模糊参数"的实现也有问题.  @minggo

**Comment by PatriceJiang** [comment]
> 引擎层面主要依赖 canvas 的 API，引擎适配层如果能够保证接口兼容，对于字体显示的影响不会很大，

出于性能考虑, 新的实现没有使用 canvas API. 

> 问题就主要在对齐排版上面，当前版本中的 2dx 中 canvas 的实现对 baseline 以及一些字体效果例如阴影都没有支持。

目前的实现支持了大部分效果, 这里的排版和效果的差异如何处理就是需要讨论的. 


>  SDF的字体支持可以作为一个额外字体支持选项，看需求引擎层面可以添加。

这里的 SDF 参考了 Unity 中TextMesh 的使用, 可以扩展支持更多的效果. 比如多重纹理. 
引擎层面可能涉及到 runtime 的问题需要确认

> 最新的修改需要新的引擎版本匹配新的2dx版本，runtime 的运行环境应该只有一个固定版本？因为底层 canvas 实现的版本原因是否会导致运行在runtime环境下的字体出现问题

字体渲染依赖于 canvas, canvas 实现在不同平台存在差异
