### ISSUE TITLE
some questions about branch 3d-gfx

### ISSUE THREAD

**Issue by Sorrowful-free** [cocos-creator/cocos2d-x-lite#2715]
Hello CocosCreator Team! Could you answer about plans of branch [3d-gfx](https://github.com/cocos-creator/cocos2d-x-lite/tree/3d-gfx)[](url)

_i am sorry for creating empty issue, but i can find any road map in English_

> It compatible with current cocos creator releases?
> when it will be release and merge to master?
> do you have any plans for support game console, nintendo switch for example?

i thank you for your work, you are awesome!

**Comment by minggo** [comment]
> It compatible with current cocos creator releases?

It will be used in creator 3.0( the version that 2D and 3D are merged in one product). The beta version will be released at the end of this year.

> do you have any plans for support game console, nintendo switch for example?

Nintendo switch may be supported next year, and there is not plan for other consoles.

**Comment by Sorrowful-free** [comment]
Thank you for your reply, i close the issue and hope It will help somebody else!
