### ISSUE TITLE
cache manager bug

### ISSUE THREAD

**Issue by neufeng** [cocos-creator/cocos2d-x-lite#2727]
iOS下，app每次启动沙盒路径是会变的，现在缓存的cacheList.json中存了绝对路径，这样下次加载时，因为路径改变了，会找不到图片、音频等。应该只存一个相对路径，沙盒路径每次实时获取拼接出绝对路径。
是大家都不用远程图片么?!!!
<img width="1020" alt="屏幕快照 2020-08-27 下午12 36 46" src="https://user-images.githubusercontent.com/3053458/91384788-082fa280-e862-11ea-98bc-de37a408091d.png">
这个bug貌似一直存在。
我用的是最新的 Cocos Creator 2.4.2
@pandamicro

**Comment by holycanvas** [comment]
https://github.com/cocos-creator-packages/jsb-adapter/pull/311, 这个 pr 修复了，2.4.3 就正常了
