### ISSUE TITLE
GFXCmdType::END_RENDER_PASS的bug

### ISSUE THREAD

**Issue by zhaijialong** [cocos-creator/cocos2d-x-lite#2785]
https://github.com/cocos-creator/cocos2d-x-lite/blob/3d-gfx/cocos/renderer/gfx-gles3/GLES3Commands.cc#L1544

endrenderpass应该去判断store op，而不是load op

**Comment by minggo** [comment]
嗯，是的。

**Comment by Mee-gu** [comment]
fixed in [cocos2d-x-lite/pull#2786](https://github.com/cocos-creator/cocos2d-x-lite/pull/2786)
