### ISSUE TITLE
Android的 gradle 版本什么时候能升级到 3.5以上  现在变现SDK都解不了了，连崩溃统计SDK都接不了

### ISSUE THREAD

**Issue by anygo** [cocos-creator/cocos2d-x-lite#2878]
Android的 gradle 版本什么时候能升级到 3.5以上  现在变现SDK都解不了了，连崩溃统计SDK都接不了，越来越多的SDK都要求 gradle  3.5以上了

**Comment by minggo** [comment]
gradle 版本也可以自己修改的，用新版本的 Android Studio 打开，会提示升级，升级一下就可以了，和引擎没什么太大关系。

**Comment by anygo** [comment]
有升级教程吗？ 升级之后编译不过

**Comment by minggo** [comment]
没有。是什么错误？

**Comment by anygo** [comment]
Failed to create parent directory 'E:\Test\NewProject_2\build\jsb-link\frameworks\runtime-src\proj.android-studio\app\task ':NewProject_2:mergeDebugAssets' property 'outputDir'' when creating directory 'E:\Test\NewProject_2\build\jsb-link\frameworks\runtime-src\proj.android-studio\app\task ':NewProject_2:mergeDebugAssets' property 'outputDir'\assets\internal'


这个配置不知道要改成什么：

android.applicationVariants.all { variant ->
    // delete previous files first
    delete "${buildDir}/intermediates/merged_assets/${variant.dirName}"

    variant.mergeAssets.doLast {
        def sourceDir = "${buildDir}/../../../../.."

        copy {
            from "${sourceDir}/assets"
            into "${outputDir}/assets"
        }

        copy {
            from "${sourceDir}/src"
            into "${outputDir}/src"
        }

        copy {
            from "${sourceDir}/jsb-adapter"
            into "${outputDir}/jsb-adapter"
        }

        copy {
            from "${sourceDir}/main.js"
            from "${sourceDir}/project.json"
            into outputDir
        }
    }
}

**Comment by minggo** [comment]
这个是在创建目录时出错了，应该和 gradle 也没关系。@PatraceJiang 你知道什么问题吗？

**Comment by minggo** [comment]
@PatriceJiang

**Comment by anygo** [comment]
Creator  2.4.2  创建的空项目
Android Studio 4.0.2
Gradle Plugin 版本 3.5.0  （使用3.2.0没有问题  只要大于3.2.0就报错）

**Comment by PatriceJiang** [comment]
报错部分修复可以参考

https://github.com/cocos-creator/cocos2d-x-lite/blob/9a6226a5118b4139dd1b696315de9d6368be2201/templates/template-link/platforms/android/app/build.gradle#L77-L120

原先的做法过时了. 

 升级 4.0 还需要修改 android instant 的 gradle 脚本.  如果用不到 android instant 可以临时把对应的 module 给删除.

**Comment by yefangqingchen** [comment]
@anygo 你解决了吗，我参考楼上的还是不行，复制不进去

**Comment by yefangqingchen** [comment]
android.applicationVariants.all { variant ->
    // delete previous files first
    delete "${buildDir}/intermediates/merged_assets/${variant.dirName}"

    variant.mergeAssets.doLast {
        def sourceDir = "${buildDir}/../../"
        System.out.println("______sourceDir = " + sourceDir)
        System.out.println("______outputDir = " + outputDir)

        copy {
            from "${sourceDir}/cocos-jsb/res"
            into "${outputDir}/res"
        }

//        copy {
//            from "${sourceDir}/cocos-jsb/subpackages"
//            into "${outputDir}/subpackages"
//        }

        copy {
            from "${sourceDir}/cocos-jsb/src"
            into "${outputDir}/src"
        }

        copy {
            from "${sourceDir}/cocos-jsb/jsb-adapter"
            into "${outputDir}/jsb-adapter"
        }

        copy {
            from "${sourceDir}/cocos-jsb/main.js"
            from "${sourceDir}/cocos-jsb/project.json"
            into outputDir
        }
    }
}

这个可以复制成功，其他的不可以，gradle3.6.4
        copy {
            from "${sourceDir}/cocos-jsb/main.js"
            from "${sourceDir}/cocos-jsb/project.json"
            into outputDir
        }
