### ISSUE TITLE
2.4.3版本，native 平台 graphics 顶点达到一定数量后无法继续画图

### ISSUE THREAD

**Issue by potato47** [cocos-creator/cocos2d-x-lite#2930]
论坛里有很多反馈，之前看有修复过 https://github.com/cocos-creator/cocos2d-x-lite/pull/1935
但测试了2.4.3版本仍有问题

这个是测试项目
[test-graphics.zip](https://github.com/cocos-creator/cocos2d-x-lite/files/5406910/test-graphics.zip)

使用模拟器运行，或者打包android，ios平台，在右侧空白区域不断画线，很快就会出现不能继续画的问题
![image](https://user-images.githubusercontent.com/21299133/96553294-89963500-12e7-11eb-83e2-043540e48302.png)

**Comment by PatriceJiang** [comment]
在 https://github.com/cocos-creator/cocos2d-x-lite/pull/2884 修复.  已经验证 
<img width="882" alt="Screen Shot 2020-10-27 at 12 51 59 PM" src="https://user-images.githubusercontent.com/40414978/97258485-75a48300-1853-11eb-9ff9-5583b16e7f0c.png">

**Comment by PatriceJiang** [comment]
@potato47 麻烦确认下

**Comment by potato47** [comment]
验证了是可以修复问题，但按照这个pr修改后编译报错jsb_gfx_auto.cpp有两个地方cobj->setBytes方法找不到，删掉后就正常了，想确认一下是否可以直接删掉这两行

![image](https://user-images.githubusercontent.com/21299133/97282571-c929c780-1879-11eb-8d3a-9ab347706f95.png)

![image](https://user-images.githubusercontent.com/21299133/97282825-1c9c1580-187a-11eb-8efb-f58766fee6c8.png)

**Comment by PatriceJiang** [comment]
> 想确认一下是否可以直接删掉这两行
可以删.  这个两接口已经在 PR 中移除

**Comment by potato47** [comment]
好的，感谢，结贴。
