### ISSUE TITLE
cocos2d-x-lite可以支持cocoapods导入iOS的项目中吗？

### ISSUE THREAD

**Issue by tenxun123** [cocos-creator/cocos2d-x-lite#3032]
我使用的cocoapods版本是1.10.0，

（1）使用这种方式引入：pod 'cocos2d-x-lite'  ，报错拉不下来。

（2）搜索 cocos2d-x-lite这个也搜索不到，报如下错误：

     MacBook-Pro Example % pod search cocos2d-x-lite
[!] Unable to find a pod with name, author, summary, or description matching `cocos2d\-x\-lite`

  请问该怎样引用？

**Comment by minggo** [comment]
不支持这种方式。cocos2d-x-lite 没有发布到 cocoapod.
