### ISSUE TITLE
如何编译生成.a静态库

### ISSUE THREAD

**Issue by wjcwukong** [cocos-creator/cocos2d-x-lite#3225]
目前需要生成静态库，集成到现有原生项目中，在官方里面没有找到相关资料，请教大佬指导一下

**Comment by minggo** [comment]
指的是在游戏项目中集成第三方静态库吗？引擎的版本是什么？

**Comment by wjcwukong** [comment]
> 指的是在游戏项目中集成第三方静态库吗？引擎的版本是什么？

大佬你好，目的是把CocosCreator生成的小游戏嵌入我们已有的iOS项目之中，目前使用的版本是3.0 Preview，导出来Xcode工程之后，不太清楚要需要把哪些产物导入到我们的原生工程中，官方文档里好像没有找到相关教程。

**Comment by minggo** [comment]
没有这块的支持。现在的项目是从系统层就要接入了，你得自己改成你要的工作方式。

**Comment by wjcwukong** [comment]
> 没有这块的支持。现在的项目是从系统层就要接入了，你得自己改成你要的工作方式。

谢谢大佬回复

**Comment by minggo** [comment]
不客气

**Comment by luqiuan** [comment]
你好，请问你们的静态库最后是怎么生成的呢
