### ISSUE TITLE
Bug 1.3.2 安卓上 cc.game.restart()报错

### ISSUE THREAD

**Issue by moonwalkerjay** [cocos-creator/cocos2d-x-lite#421]
4:36.458 3448 3464 D cocos2d-x debug info: Cocos2d-JS v3.13
11-28 18:44:38.453 3448 3464 E cocos js error:: /data/user/0/com.baiyou.dkd/files/blackjack-remote-asset/src/jsb_polyfill.js line:28901 msg:TypeError: cc.director.getScheduler(...)._schedule is not a function
11-28 18:44:38.454 3448 3464 D cocos2d-x debug info: Evaluating main.js failed (evaluatedOK == JS_FALSE)

**Comment by moonwalkerjay** [comment]
重现方式  只要调用cc.game.restart 就会报错加黑屏

**Comment by dumganhar** [comment]
@pandamicro, please take a look at this issue. Thanks.

**Comment by xuewuli** [comment]
同样问题，但表现不同，
void Renderer::fillVerticesAndIndices(const TrianglesCommand* cmd) {
 memcpy(&_verts[_filledVertex], cmd->getVertices(), sizeof(V3F_C4B_T2F) * cmd->getVertexCount());
这里出现single 11

**Comment by xuewuli** [comment]
经过跟踪调整最后我这里的问题定位在 SkeletonBatch的instance在Director rest的时候没有重置导致的。我自己本地修复了，是在Director 里直接引用了SkeletonBatch加了个destroyInstance，这种形式的代码不适合pr，所以还得官方看看最终怎么修

**Comment by natural-law** [comment]
> 我自己本地修复了，是在Director 里直接引用了SkeletonBatch加了个destroyInstance，这种形式的代码不适合pr，所以还得官方看看最终怎么修

好像除了这样做没有其他解决方案...

**Comment by xuewuli** [comment]
安卓的mk文件也得改一下，不然build不过吧
