### ISSUE TITLE
Button animation bug in android build CC 3.7.0

### ISSUE THREAD

**Issue by vrpv** [cocos-creator/cocos2d-x-lite#4312]
Focus instantly lost on finger movement.
![bug](https://user-images.githubusercontent.com/51680227/232309594-56299d6e-ecac-4db6-a1f6-c52df73a80e0.gif)

**Comment by minggo** [comment]
Could you please create an issue in https://github.com/cocos/cocos-engine? As engine-native is merged in into https://github.com/cocos/cocos-engine since v3.6.

**Comment by vrpv** [comment]
Moved to https://github.com/cocos/cocos-engine/issues/14803.

**Comment by minggo** [comment]
Thanks. I will close this one.
