### ISSUE TITLE
使用socketio会收到两次消息回调

### ISSUE THREAD

**Issue by springrider** [cocos-creator/cocos2d-x-lite#563]
https://github.com/cocos-creator/cocos2d-x-lite/blob/develop/cocos/network/SocketIO.cpp#L944
https://github.com/cocos-creator/cocos2d-x-lite/blob/develop/cocos/network/SocketIO.cpp#L945
不确定为什么这里这么些，但是这两行最终都会触发jsb的fireEventToScript方法，导致js那边通过
 socket.on('message', function () {})监听的话，会被调用两次.

**Comment by dumganhar** [comment]
看了代码，的确啊。。。

**Comment by jareguo** [comment]
fixed
