### ISSUE TITLE
AssetsManagerEx has a question

### ISSUE THREAD

**Issue by cnogo** [cocos-creator/cocos2d-x-lite#592]
after creator 1.4,   jsb.AssetsManager provide a function "setVersionCompareHandler"  that user can define self version compare.
but when AssetsManangerEx class is creating, AssetsManagerEx constructor function is using the default compare function (cmpVersion), because the user version compare handler can not be set when AssetsManagerEx contructor:
**the call stack:**
AssetsMangerEx:AssetsManagerEx();

AssetsManagerEx:initManifest();

AssetsManagerEx:loadLocalManifest();

Manifest:versionCreator(Manifest *b,  handler);

** the call stack end **

中文：
creator 1.4 之后， 热更提供一个 让用户自己自定义比较版本的函数("setVersionCompareHandler"), 但是 js 创建 AssetsMangerEx时，AssetsMangerEx 构造函数只提供了 manifestUrl 路径和 storagePath，这时_versionCompareHandle还没有被赋值，所以在initManifests的时候使用了默认的比较函数，然后在调用堆栈的loadLocalManifest中的如下代码就和用户设想的不一样了，（因为_versionCompareHandle使用的是默认的函数），然后可能导致一直重复更新
![image](https://cloud.githubusercontent.com/assets/15942185/25171250/bf38e22a-251f-11e7-809a-55b1fc8cf194.png)

**Comment by pandamicro** [comment]
这个问题是存在的，我已经记录下来会在 1.5 中尝试修复的

**Comment by pandamicro** [comment]
1.5 中可以用 `new jsb.AssetsManager(manifestUrl, storagePath, versionCompareHandle);` 来让 versionCompare handle 立即生效
