### ISSUE TITLE
CCLabel存在性能问题，请看描述

### ISSUE THREAD

**Issue by colinsusie** [cocos-creator/cocos2d-x-lite#701]
Creator创建TTF类型的Label时默认的字体大小是40，如果游戏中不使用40的字体，会存在一个很大的性能问题。比如一个界面有几十个大小为20的Label，此时CCLabel的工作情况如下：

1. 创建CCLabel，Creator传入默认大小为40，此时FontAtlasCache会创建一个FontAtlas，用于存放40大小的文字。而FontAtlas会预先创建一个512x512的Texture
2. 接着Creator将Label字体大小改为20，CCLabel的setTTFConfig被调用，然后FontAtlasCache会再创建另一个FontAtlas用于存放20大小的文字。
3. 问题来了：**那个40的FontAtlas因为引用计算变为0，因此被释放掉了**。当我创建几十个Label的时候，实际上一直在创建和释放那个40的FontAtlas，也即有一个512*512的Texture，在创建Label的过程当中，不断的被创建出来然后释放掉。

这个在文字信息很多的界面，性能消耗非常明显，我们项目优化掉这个以后，一个可以省掉250ms以上的时间

希望官方想一个更好的方案，我这里给一个建议是，引用计数为0的FontAtlas，不马上释放掉，而是放入一个LRUCache里，方便下次快速重用。

**Comment by zilongshanren** [comment]
感谢建议，如果不马上释放，你指的是下次有使用相同字号的 Label 的时候，重新启用这个 FontAtlas 么？能否把你修改的 diff 贴一下看看？

目前生成 fontAtlas 的逻辑不只是字号大小，还有描边大小也会有影响。

**Comment by zilongshanren** [comment]
同一个 ttf 字体，不同字号的label 渲染，我之前有考虑用 SDF 来做，原理也是你说的尽量减少 FontAtlas 的创建。

**Comment by WenhaiLin** [comment]
@zilongshanren 楼主的意思应该是修改FontAtlas的释放机制，基于LRU算法控制，而不是简单的引用计数。
SDF有待你继续优化😏😏😏

**Comment by zilongshanren** [comment]
@colinsusie 是这样么？ FontAtlas 的释放用 LRU 来控制？

**Comment by colinsusie** [comment]
> 如果不马上释放，你指的是下次有使用相同字号的 Label 的时候，重新启用这个 FontAtlas 么？能否把你修改的 diff 贴一下看看？

马上释放的话就会有我上面描述的问题，我根本没有用到40的文字，然后这个40就会不断的创建和释放，性能的根源在这里

**Comment by jareguo** [comment]
其实我觉得这里比较简单的处理方式，是延迟到一帧结束时才创建 FontAtlas

**Comment by colinsusie** [comment]
@zilongshanren是的，引用计数为0不马上释放，用LRU控制，这样就解决这个不断创建释放的问题，但这个只是一个建议。
我觉得应该在创建Label的时候，不使用40这个默认字体，而是根据我在Creator中设置的那个字号创建。这样能减掉这个没有用的40号的Atlas

**Comment by zilongshanren** [comment]
@colinsusie 
恩，这个创建过程需要优化，在资源的释放上面暂时没必要引擎 LRU来增加复杂度。我晚点提交 PR fix 一下，到时候也麻烦你帮忙验证一下优化效果。再次感谢指出这个问题。 👍

**Comment by colinsusie** [comment]
@jareguo 嗯，你这个方法更简单一些，不过我好好考虑有没有其他BUG的可能。
@zilongshanren，我其实没有去优化它，所以就不贴diff代码了，因为我只是粗暴的不让引用计算为0的纹理释放。因为我们项目我能把控得了，我知道不会有很多字号和样式出现。但引擎就不能这么简单了：）

**Comment by xulidong** [comment]
之前项目用到的cocos stuio 1.6也存在这样的问题，我们项目组自己做了优化。
看了一下优化记录，之前一个UIText会创建三次纹理：
>
第一次，UIText在构造的时候使用过默认fontName和fontSize创建第一次字体纹理;
第二次，从CSB读取到fontName后，使用新的fontName和默认fontSize，创建第二张纹理，释放第一张；
第三次，在CSB读取到fontSize后，使用新的fontName和fontSize，创建第三章，释放第二张。

在设置的字体和大小都跟默认字体不一样时，每一个Label就会创建三张纹理，然后释放前两张，导致在label比较多的界面，会不断的创建释放纹理，打开非常慢。

我们的优化方式是：
>1  去掉了构造函数中的纹理，省掉第一张纹理；
>2 将setFontName和setFontSize合并成为一个函数，将第二三张纹理变为一张。

ccc也可以借鉴这种处理方式，直接把默认的纹理去掉，读取到ccc中设置的纹理之后，一次性创建一张字体纹理即可。

**Comment by ayang008** [comment]
@zilongshanren 请问是否已经有针对性的优化pr?
个人感觉是不是直接把默认的40改成自己游戏最多使用的字号就可以了~.~
