### ISSUE TITLE
1.6.0 关于setLocalZOrder的bug

### ISSUE THREAD

**Issue by lich2333** [cocos-creator/cocos2d-x-lite#801]
在web平台测试了下 setLocalZOrder方法是正常作用的, 但是在模拟器和原生平台上， 在同一个父节点下的不同子节点 a、b、c 、d 调用setLocalZOrder 设置a层级为 1 ，b层级为2，c层级为3，d层级为4. 然后将d节点隐藏 会导致a节点渲染在 b、c节点之上。 显示上就是a节点遮盖了b、c节点。
在1.5.1上测试 原生和h5 模拟器都是正常的。。。

**Comment by jareguo** [comment]
能不能提交一个 demo？
